stages:
  - test

build:
  stage: test
  script:
    - "apply_overlay bc-java ./"
    - "bash installbetas.sh \"$(curl https://downloads.bouncycastle.org/betas/beta.ver)\" \"./bc-jars-reg\""
    - ". cienv.sh; \ gradle clean build test"
  